const formData = {
  foodTypes: [
    'breads',
    'breakfast',
    'cakes',
    'casseroles',
    'cookies',
    'desserts',
    'dinner',
    'dips',
    'drinks',
    'fish',
    'grilling',
    'bbq',
    'sandwiches',
    'baked',
    'fried'
  ],
  meats: [
    'chicken breast',
    'ground beef',
    'bacon',
    'sausage',
    'beef steak',
    'ham',
    'hot dog',
    'pork chops',
    'chicken thighs',
    'ground turkey',
    'cooked chicken',
    'turkey',
    'pork',
    'pepperoni',
    'whole chicken',
    'chicken leg',
    'ground pork',
    'chorizo',
    'chicken wings',
    'beef roast',
    'polish sausage',
    'salami',
    'pork roast',
    'ground chicken',
    'pork ribs',
    'spam',
    'venison',
    'pork shoulder',
    'bologna',
    'bratwurst',
    'prosciutto',
    'lamb',
    'corned beef',
    'chicken roast',
    'lamb chops',
    'pancetta',
    'ground lamb',
    'beef ribs',
    'duck',
    'pork belly',
    'beef liver',
    'leg of lamb',
    'canadian bacon',
    'beef shank',
    'veal',
    'chicken giblets',
    'cornish hen',
    'lamb shoulder',
    'lamb shank',
    'deer',
    'ground veal',
    'pastrami',
    'rabbit',
    'sliced turkey',
    'pork loin',
    'elk',
    'beef suet',
    'veal cutlet',
    'lamb loin',
    'marrow bones',
    'goose',
    'chicken tenders',
    'veal chops',
    'quail',
    'oxtail',
    'pheasant',
    'lamb liver',
    'moose',
    'turkey liver',
    'pork liver',
    'veal shank',
    'foie gras',
    'beef sirloin',
    'liver sausage',
    'sweetbread',
    'wild boar',
    'snail',
    'pigeon',
    'duck liver',
    'goose liver',
    'grouse',
    'ostrich',
    'soppressata',
    'alligator'
  ],
  seasoning: ['black pepper', 'salt'],
  vegetables: [
    'onion',
    'garlic',
    'tomato',
    'potato',
    'carrot',
    'bell pepper',
    'basil',
    'parsley',
    'broccoli',
    'corn',
    'spinach',
    'mushroom',
    'green beans',
    'ginger',
    'chili pepper',
    'celery',
    'rosemary',
    'salad greens',
    'red onion',
    'cucumber',
    'sweet potato',
    'pickle',
    'avocado',
    'zucchini',
    'cilantro',
    'frozen vegetables',
    'olive',
    'asparagus',
    'cabbage',
    'cauliflower',
    'dill',
    'kale',
    'mixed vegetable',
    'pumpkin',
    'squash',
    'mint',
    'scallion',
    'sun dried tomato',
    'shallot',
    'eggplant',
    'beet',
    'butternut squash',
    'horseradish',
    'leek',
    'caper',
    'brussels sprout',
    'artichoke heart',
    'chia seeds',
    'radish',
    'sauerkraut',
    'artichoke',
    'portobello mushroom',
    'sweet pepper',
    'arugula',
    'spaghetti squash',
    'capsicum',
    'bok choy',
    'parsnip',
    'okra',
    'yam',
    'fennel',
    'turnip',
    'snow peas',
    'bean sprouts',
    'seaweed',
    'chard',
    'collard',
    'canned tomato',
    'pimiento',
    'watercress',
    'tomatillo',
    'rocket',
    'mustard greens',
    'bamboo shoot',
    'rutabaga',
    'endive',
    'broccoli rabe',
    'jicama',
    'kohlrabi',
    'hearts of palm',
    'butternut',
    'celery root',
    'daikon',
    'radicchio',
    'porcini',
    'chinese broccoli',
    'jerusalem artichoke',
    'cress',
    'water chestnut',
    'dulse',
    'micro greens',
    'burdock',
    'chayote'
  ],
  fruits: [
    'lemon',
    'apple',
    'banana',
    'lime',
    'strawberry',
    'orange',
    'pineapple',
    'blueberry',
    'raisin',
    'coconut',
    'grape',
    'peach',
    'raspberry',
    'cranberry',
    'mango',
    'pear',
    'blackberry',
    'cherry',
    'date',
    'watermelon',
    'berries',
    'kiwi',
    'grapefruit',
    'mandarin',
    'craisins',
    'cantaloupe',
    'plum',
    'apricot',
    'clementine',
    'prunes',
    'apple butter',
    'pomegranate',
    'nectarine',
    'fig',
    'tangerine',
    'papaya',
    'rhubarb',
    'sultanas',
    'plantain',
    'currant',
    'passion fruit',
    'guava',
    'persimmons',
    'lychee',
    'lingonberry',
    'tangelos',
    'kumquat',
    'boysenberry',
    'star fruit',
    'quince',
    'honeydew',
    'crabapples'
  ],
  sweeteners: [
    'sugar',
    'brown sugar',
    'honey',
    'confectioners sugar',
    'maple syrup',
    'corn syrup',
    'molasses',
    'artificial sweetener',
    'agave nectar'
  ]
}

module.exports = formData
